"""empty message

Revision ID: 80b6b4cea6b5
Revises:
Create Date: 2026-04-12 22:02:28.210092

"""

from collections.abc import Sequence  # noqa

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80b6b4cea6b5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_recipes_app_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site_recipes_app_recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("steps", sa.String(), nullable=False),
        sa.Column("ingredients", sa.String(), nullable=False),
        sa.Column("time_cooking", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "site_recipes_app_recipe_category",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["site_recipes_app_category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["site_recipes_app_recipe.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("site_recipes_app_recipe_category")
    op.drop_table("site_recipes_app_recipe")
    op.drop_table("site_recipes_app_category")
    # ### end Alembic commands ###
